tracks:
  - url: http://wonder.wisdom-guild.net/price/Flusterstorm/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: FlusterStrom(Foil)
    exp:
      ignore:
        - IMA
  - url: http://wonder.wisdom-guild.net/price/Preordain/?set%5B%5D=&lang%5B%5D=&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: Preordain(Foil)
