tracks:
  - url: http://wonder.wisdom-guild.net/price/Flusterstorm/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: [Judge] Flusterstorm/狼狽の嵐 EX
    exp:
      ignore:
        - IMA
  - url: http://wonder.wisdom-guild.net/price/Preordain/?set%5B%5D=&lang%5B%5D=&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: [Foil] Preordain/定業
  - url: http://wonder.wisdom-guild.net/price/Force+of+Will/?set%5B%5D=&lang%5B%5D=&state_code=&price_gt=32000&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: [Judge] Force of Will/意思の力 EX+
  - url: http://wonder.wisdom-guild.net/price/Scalding+Tarn/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: [Foil] 沸騰する小湖/Scalding Tarn
  - url: http://wonder.wisdom-guild.net/price/Scalding+Tarn/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: [ZEN Expedition] 沸騰する小湖/Scalding Tarn
    exp:
      ignore:
        - ZEN
        - MM3
