tracks:
  - url: http://wonder.wisdom-guild.net/price/Flusterstorm/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: Judge Flusterstorm/狼狽の嵐 EX
    exp:
      ignore:
          - IMA
  - url: http://wonder.wisdom-guild.net/price/Dack+Fayden/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&quality%5B%5D=promo&stock_gt=1&stock_lt=#ptable
    exp:
      ignore:
          - EMA
  - url: http://wonder.wisdom-guild.net/price/Bazaar+of+Baghdad/?stock_gt=1
  - url: http://wonder.wisdom-guild.net/price/Force+of+Will/?set%5B%5D=&lang%5B%5D=&state_code=&price_gt=37000&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: Judge Force of Will/意思の力 EX+
  - url: http://wonder.wisdom-guild.net/price/Force+of+Negation/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: Foil Force of Negation
  - url: http://wonder.wisdom-guild.net/price/Dockside+Extortionist/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Urza%2C+Lord+High+Artificer/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Cavern+Harpy/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Once+Upon+a+Time/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Ice-Fang+Coatl/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Polluted+Delta/?set%5B%5D=&lang%5B%5D=&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    exp:
      ignore:
          - KTK
  - url: http://wonder.wisdom-guild.net/price/Mishra%27s+Workshop/?set%5B%5D=&lang%5B%5D=&state_code=EX%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Uro%2C+Titan+of+Nature%27s+Wrath/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    exp:
      ignore:
          - THB
  - url: http://wonder.wisdom-guild.net/price/Brazen+Borrower/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
      exp:
      ignore:
          - ELD
  - url: http://wonder.wisdom-guild.net/price/Lurrus+of+the+Dream-Den/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
      exp:
      ignore:
          - IKO
  - url: http://wonder.wisdom-guild.net/price/Ice-Fang+Coatl/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Fierce+Guardianship/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
