tracks:
  - url: http://wonder.wisdom-guild.net/price/Bazaar+of+Baghdad/?stock_gt=1
  - url: http://wonder.wisdom-guild.net/price/Mishra%27s+Workshop/?stock_gt=1
  - url: http://wonder.wisdom-guild.net/price/Polluted+Delta/?set%5B%5D=ONS&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: ONS Foil Polluted Delta
  - url: http://wonder.wisdom-guild.net/price/Flooded+Strand/?set%5B%5D=ONS&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: ONS Foil Flooded Strand
  - url: http://wonder.wisdom-guild.net/price/Underground+Sea/?set%5B%5D=3ED&lang%5B%5D=GER&state_code=&price_gt=140000&price_lt=&stock_gt=1&stock_lt=#ptable
    name: FBB GER Underground Sea
  - url: http://wonder.wisdom-guild.net/price/Badlands/?set%5B%5D=3ED&lang%5B%5D=GER&state_code=&price_gt=100000&price_lt=&stock_gt=1&stock_lt=#ptable
    name: FBB GER Badlands
  - url: http://wonder.wisdom-guild.net/price/Bayou/?set%5B%5D=3ED&lang%5B%5D=GER&state_code=&price_gt=100000&price_lt=&stock_gt=1&stock_lt=#ptable
    name: FBB GER Bayou
  - url: http://wonder.wisdom-guild.net/price/Leyline+of+the+Void/?set%5B%5D=&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: TSR Foil Leyline of the Void
    exp:
      ignore:
        - GPT
        - M11
        - M20
  - url: http://wonder.wisdom-guild.net/price/Wasteland/?quality%5B0%5D=foil&quality%5B1%5D=promo&lang%5B0%5D=ENG&price_gt=30000&stock_gt=1
    name: Promo Wasteland
  - url: http://wonder.wisdom-guild.net/price/Dark+Ritual/?set%5B%5D=MMQ&lang%5B%5D=ENG&state_code=&price_gt=&price_lt=&quality%5B%5D=foil&stock_gt=1&stock_lt=#ptable
    name: MMQ Foil Dark Ritual
