tracks:
  - url: http://wonder.wisdom-guild.net/price/Walking+Ballista/?set%5B%5D=&lang%5B%5D=&state_code=NM%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
    name: 歩行バリスタ NM
  - url: http://wonder.wisdom-guild.net/price/Teferi%2C+Hero+of+Dominaria/?set%5B%5D=&lang%5B%5D=&state_code=NM%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
    name: ドミナリアの英雄、テフェリー NM
  - url: http://wonder.wisdom-guild.net/price/Reality+Smasher/?set%5B%5D=&lang%5B%5D=&state_code=NM%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Jace%2C+Architect+of+Thought/?set%5B%5D=RTR&lang%5B%5D=ENG&state_code=NM%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Sphinx%27s+Revelation/?set%5B%5D=RTR&lang%5B%5D=&state_code=NM%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Courser+of+Kruphix/?stock_gt=1
  - url: http://wonder.wisdom-guild.net/price/Dig+Through+Time/?stock_gt=1
