tracks:
  - url: http://wonder.wisdom-guild.net/price/Reality+Smasher/?set%5B%5D=&lang%5B%5D=&state_code=NM%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Jace%2C+Architect+of+Thought/?set%5B%5D=RTR&lang%5B%5D=ENG&state_code=NM%3A&price_gt=&price_lt=&stock_gt=1&stock_lt=#ptable
  - url: http://wonder.wisdom-guild.net/price/Courser+of+Kruphix/?stock_gt=1
