name: CI

# on:
#   schedule:
#   - cron: 0 * * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Rstart
      run: yarn install
    - name: Rstart
      run: yarn start
