name: Run hourly jobs

# on: push
on:
  schedule:
    - cron: 0 * * * *
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - uses: actions/cache@v1
#       with:
#         path: node_modules
#         key: ${{ runner.os }}-node-${{ github.event_name }}-${{ hashFiles('**/yarn.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-node-${{ github.event_name }}-
    - run: yarn install
    - name: start
      run: yarn start --job track-whisper --job alert-stocks --slack ${{ secrets.SLACK_INCOMING_HOOK_KEY }} --configs ./config --firebase ${{ secrets.FIREBASE_ACCESS_KEY }}
