name: test action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: yarn install
    - name: start
      run: yarn testr
      env:
        WHY: ${{ secrets.WHY }}
